AWSTemplateFormatVersion: '2010-09-09'
Description: Baseline - IAM Password Policy Settings

Metadata:
  Stack:
    Value: 0
  VersionDate:
    Value: 2020-10-18
  Identifier:
    Value: password-policy
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Password Policy Settings
        Parameters:
          - pMaxPasswordAge
          - pMinPasswordLength
          - pPasswordHistory
          - pRequireUppercaseChars
          - pRequireLowercaseChars
          - pRequireNumbers
          - pRequireSymbols
    ParameterLabels:
      pMaxPasswordAge:
        default: Max Password Age
      pMinPasswordLength:
        default: Minimum Password Length
      pPasswordHistory:
        default: Password History
      pRequireLowercaseChars:
        default: Require Lowercase Chars
      pRequireNumbers:
        default: Require Numbers
      pRequireSymbols:
        default: Require Symbols
      pRequireUppercaseChars:
        default: Require Uppercase Chars

Parameters:
  pMaxPasswordAge:
    Type: 'Number'
    Description: 'Maximum age for passwords'
    Default: 90
    ConstraintDescription: '(90-365 days)'
    MinValue: 90
    MaxValue: 365
  pMinPasswordLength:
    Type: 'Number'
    Description: 'Minimum password length'
    Default: 14
    ConstraintDescription: '(8-128 characters)'
    MinValue: 8
    MaxValue: 128
  pPasswordHistory:
    Type: 'Number'
    Description: 'Number of previous passwords to remember'
    Default: 24
    ConstraintDescription: '(1-24 passwords)'
    MinValue: 1
    MaxValue: 24
  pRequireLowercaseChars:
    Type: 'String'
    Description: 'Require at least one lowercase character'
    Default: 'True'
    AllowedValues:
    - 'True'
    - 'False'
  pRequireNumbers:
    Type: 'String'
    Description: 'Require at least one number'
    Default: 'True'
    AllowedValues:
    - 'True'
    - 'False'
  pRequireSymbols:
    Type: 'String'
    Description: 'Require at least one symbol'
    Default: 'True'
    AllowedValues:
    - 'True'
    - 'False'
  pRequireUppercaseChars:
    Type: 'String'
    Description: 'Require at least one uppercase character'
    Default: 'True'
    AllowedValues:
    - 'True'
    - 'False'

Resources:

  rIAMPasswordPolicy:
    Type: 'Custom::IAMPolicyResource'
    Properties:
      ServiceToken: !GetAtt rIAMPasswordPolicyResource.Arn
      Region: !Ref "AWS::Region"

  rIAMPasswordPolicyResource:
    Type: "AWS::Lambda::Function"
    Properties:
      Runtime: python3.7
      Handler: index.lambda_handler
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt rIAMPasswordPolicyResourceExecutionRole.Arn
      Code:
        ZipFile: !Sub |
          import boto3
          from botocore.exceptions import ClientError
          import json
          import cfnresponse
          iam = boto3.client("iam")
          # Lambda entry point
          def lambda_handler(event, context):
            if event['RequestType'] == 'Create' or event['RequestType'] == 'Update':
              res, reason = update_policy()
            elif event['RequestType'] == 'Delete':
              res, reason = delete_policy()
            else:
              res = False
              reason = "Unknown operation: " + event['RequestType']
            responseData = {}
            responseData['Reason'] = reason
            if res:
              cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)
            else:
              cfnresponse.send(event, context, cfnresponse.FAILED, responseData)
          def update_policy():
            try:
              response = iam.update_account_password_policy(
                  AllowUsersToChangePassword=True,
                  HardExpiry=False,
                  MaxPasswordAge=${pMaxPasswordAge},
                  MinimumPasswordLength=${pMinPasswordLength},
                  RequireLowercaseCharacters=${pRequireLowercaseChars},
                  RequireNumbers=${pRequireNumbers},
                  RequireSymbols=${pRequireSymbols},
                  RequireUppercaseCharacters=${pRequireUppercaseChars},
                  PasswordReusePrevention=${pPasswordHistory})
              return(True, response)
            except Exception as e:
              return (False, "Cannot update policy: " + str(e))
          def delete_policy():
            try:
              policy = iam.get_account_password_policy()
              response = iam.delete_account_password_policy()
              return (True, response)
            except Exception as e:
              return (False, "Cannot delete policy: " + str(e))

  rIAMPasswordPolicyResourceExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: IAMPasswordCreatorPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: 'Allow'
            Action:
            - 'logs:CreateLogGroup'
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
            Resource: '*'
          - Effect: Allow
            Action:
              - iam:GetAccountPasswordPolicy
              - iam:UpdateAccountPasswordPolicy
              - iam:DeleteAccountPasswordPolicy
            Resource: "*"
